// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-counter/grpc"
	"github.com/asynccnu/ccnubox-be/be-counter/ioc"
	"github.com/asynccnu/ccnubox-be/be-counter/pkg/grpcx"
	"github.com/asynccnu/ccnubox-be/be-counter/repository/cache"
	"github.com/asynccnu/ccnubox-be/be-counter/service"
)

// Injectors from wire.go:

func InitGRPCServer() grpcx.Server {
	cmdable := ioc.InitRedis()
	counterCache := cache.NewRedisCounterCache(cmdable)
	logger := ioc.InitLogger()
	counterService := service.NewCachedCounterService(counterCache, logger)
	counterServiceServer := grpc.NewCounterServiceServer(counterService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxKratosServer(counterServiceServer, client, logger)
	return server
}
