// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Registry      *Registry              `protobuf:"bytes,3,opt,name=registry,proto3" json:"registry,omitempty"`
	Zaplog        *ZapLogConfigs         `protobuf:"bytes,4,opt,name=zaplog,proto3" json:"zaplog,omitempty"`
	Schoolday     *SchoolDay             `protobuf:"bytes,5,opt,name=schoolday,proto3" json:"schoolday,omitempty"`
	Defaults      *Defaults              `protobuf:"bytes,6,opt,name=defaults,proto3" json:"defaults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetRegistry() *Registry {
	if x != nil {
		return x.Registry
	}
	return nil
}

func (x *Bootstrap) GetZaplog() *ZapLogConfigs {
	if x != nil {
		return x.Zaplog
	}
	return nil
}

func (x *Bootstrap) GetSchoolday() *SchoolDay {
	if x != nil {
		return x.Schoolday
	}
	return nil
}

func (x *Bootstrap) GetDefaults() *Defaults {
	if x != nil {
		return x.Defaults
	}
	return nil
}

type Server struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Grpc                *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	WaitCrawTime        int32                  `protobuf:"varint,3,opt,name=waitCrawTime,proto3" json:"waitCrawTime,omitempty"`               // 等待爬虫抓取数据的时间,单位ms
	ClassExpiration     int32                  `protobuf:"varint,4,opt,name=classExpiration,proto3" json:"classExpiration,omitempty"`         // 课程过期时间,单位s
	RecycleExpiration   int32                  `protobuf:"varint,5,opt,name=recycleExpiration,proto3" json:"recycleExpiration,omitempty"`     // 回收站课程过期时间,单位s
	BlackListExpiration int32                  `protobuf:"varint,6,opt,name=blackListExpiration,proto3" json:"blackListExpiration,omitempty"` // 黑名单过期时间,如果要查询的课程在数据库不存在,列入黑名单,单位s
	WaitUserSvcTime     int32                  `protobuf:"varint,7,opt,name=waitUserSvcTime,proto3" json:"waitUserSvcTime,omitempty"`         // 等待用户服务的时间,单位ms
	RefreshInterval     int32                  `protobuf:"varint,8,opt,name=refreshInterval,proto3" json:"refreshInterval,omitempty"`         // 刷新间隔时间,单位s
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Server) GetWaitCrawTime() int32 {
	if x != nil {
		return x.WaitCrawTime
	}
	return 0
}

func (x *Server) GetClassExpiration() int32 {
	if x != nil {
		return x.ClassExpiration
	}
	return 0
}

func (x *Server) GetRecycleExpiration() int32 {
	if x != nil {
		return x.RecycleExpiration
	}
	return 0
}

func (x *Server) GetBlackListExpiration() int32 {
	if x != nil {
		return x.BlackListExpiration
	}
	return 0
}

func (x *Server) GetWaitUserSvcTime() int32 {
	if x != nil {
		return x.WaitUserSvcTime
	}
	return 0
}

func (x *Server) GetRefreshInterval() int32 {
	if x != nil {
		return x.RefreshInterval
	}
	return 0
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Data_Database         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	Kafka         *Data_Kafka            `protobuf:"bytes,3,opt,name=kafka,proto3" json:"kafka,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Data) GetKafka() *Data_Kafka {
	if x != nil {
		return x.Kafka
	}
	return nil
}

type Etcd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Etcd) Reset() {
	*x = Etcd{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Etcd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Etcd) ProtoMessage() {}

func (x *Etcd) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Etcd.ProtoReflect.Descriptor instead.
func (*Etcd) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Etcd) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Etcd) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Etcd) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Registry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Etcd          *Etcd                  `protobuf:"bytes,1,opt,name=etcd,proto3" json:"etcd,omitempty"`
	Usersvc       string                 `protobuf:"bytes,2,opt,name=usersvc,proto3" json:"usersvc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registry) Reset() {
	*x = Registry{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry) ProtoMessage() {}

func (x *Registry) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry.ProtoReflect.Descriptor instead.
func (*Registry) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Registry) GetEtcd() *Etcd {
	if x != nil {
		return x.Etcd
	}
	return nil
}

func (x *Registry) GetUsersvc() string {
	if x != nil {
		return x.Usersvc
	}
	return ""
}

type ZapLogConfigs struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LogLevel          string                 `protobuf:"bytes,1,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`                                 // 日志打印级别 debug, info, warning, error
	LogFormat         string                 `protobuf:"bytes,2,opt,name=log_format,json=logFormat,proto3" json:"log_format,omitempty"`                              // 输出日志格式 logfmt, json
	LogPath           string                 `protobuf:"bytes,3,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`                                    // 输出日志文件路径
	LogFileName       string                 `protobuf:"bytes,4,opt,name=log_file_name,json=logFileName,proto3" json:"log_file_name,omitempty"`                      // 输出日志文件名称
	LogFileMaxSize    int32                  `protobuf:"varint,5,opt,name=log_file_max_size,json=logFileMaxSize,proto3" json:"log_file_max_size,omitempty"`          // 【日志分割】单个日志文件最多存储量 单位(mb)
	LogFileMaxBackups int32                  `protobuf:"varint,6,opt,name=log_file_max_backups,json=logFileMaxBackups,proto3" json:"log_file_max_backups,omitempty"` // 【日志分割】日志备份文件最多数量
	LogMaxAge         int32                  `protobuf:"varint,7,opt,name=log_max_age,json=logMaxAge,proto3" json:"log_max_age,omitempty"`                           // 日志保留时间，单位: 天 (day)
	LogCompress       bool                   `protobuf:"varint,8,opt,name=log_compress,json=logCompress,proto3" json:"log_compress,omitempty"`                       // 是否压缩日志
	LogStdout         bool                   `protobuf:"varint,9,opt,name=log_stdout,json=logStdout,proto3" json:"log_stdout,omitempty"`                             // 是否输出到控制台
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ZapLogConfigs) Reset() {
	*x = ZapLogConfigs{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZapLogConfigs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZapLogConfigs) ProtoMessage() {}

func (x *ZapLogConfigs) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZapLogConfigs.ProtoReflect.Descriptor instead.
func (*ZapLogConfigs) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *ZapLogConfigs) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *ZapLogConfigs) GetLogFormat() string {
	if x != nil {
		return x.LogFormat
	}
	return ""
}

func (x *ZapLogConfigs) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

func (x *ZapLogConfigs) GetLogFileName() string {
	if x != nil {
		return x.LogFileName
	}
	return ""
}

func (x *ZapLogConfigs) GetLogFileMaxSize() int32 {
	if x != nil {
		return x.LogFileMaxSize
	}
	return 0
}

func (x *ZapLogConfigs) GetLogFileMaxBackups() int32 {
	if x != nil {
		return x.LogFileMaxBackups
	}
	return 0
}

func (x *ZapLogConfigs) GetLogMaxAge() int32 {
	if x != nil {
		return x.LogMaxAge
	}
	return 0
}

func (x *ZapLogConfigs) GetLogCompress() bool {
	if x != nil {
		return x.LogCompress
	}
	return false
}

func (x *ZapLogConfigs) GetLogStdout() bool {
	if x != nil {
		return x.LogStdout
	}
	return false
}

type SchoolDay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HolidayTime   string                 `protobuf:"bytes,1,opt,name=holidayTime,proto3" json:"holidayTime,omitempty"` //放假日期(正式放假的第一天)
	SchoolTime    string                 `protobuf:"bytes,2,opt,name=schoolTime,proto3" json:"schoolTime,omitempty"`   //上学日期(正式上学的第一天)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchoolDay) Reset() {
	*x = SchoolDay{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchoolDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolDay) ProtoMessage() {}

func (x *SchoolDay) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolDay.ProtoReflect.Descriptor instead.
func (*SchoolDay) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *SchoolDay) GetHolidayTime() string {
	if x != nil {
		return x.HolidayTime
	}
	return ""
}

func (x *SchoolDay) GetSchoolTime() string {
	if x != nil {
		return x.SchoolTime
	}
	return ""
}

// 前端不传参时使用的默认值
type Defaults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	Semester      string                 `protobuf:"bytes,2,opt,name=semester,proto3" json:"semester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Defaults) Reset() {
	*x = Defaults{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Defaults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Defaults) ProtoMessage() {}

func (x *Defaults) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Defaults.ProtoReflect.Descriptor instead.
func (*Defaults) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *Defaults) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *Defaults) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       int32                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"` // 超时时间,单位s
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type Data_Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	LogPath       string                 `protobuf:"bytes,2,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`               //gorm日志文件路径
	LogFileName   string                 `protobuf:"bytes,3,opt,name=log_file_name,json=logFileName,proto3" json:"log_file_name,omitempty"` //gorm日志文件名称
	LogLevel      string                 `protobuf:"bytes,4,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`            //gorm日志打印级别  info, warn, error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Data_Database) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

func (x *Data_Database) GetLogFileName() string {
	if x != nil {
		return x.LogFileName
	}
	return ""
}

func (x *Data_Database) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ReadTimeout   int32                  `protobuf:"varint,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`    //单位ms
	WriteTimeout  int32                  `protobuf:"varint,4,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"` //单位ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Redis) GetReadTimeout() int32 {
	if x != nil {
		return x.ReadTimeout
	}
	return 0
}

func (x *Data_Redis) GetWriteTimeout() int32 {
	if x != nil {
		return x.WriteTimeout
	}
	return 0
}

type Data_Kafka struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brokers       []string               `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty"` // kafka broker地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Kafka) Reset() {
	*x = Data_Kafka{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Kafka) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Kafka) ProtoMessage() {}

func (x *Data_Kafka) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Kafka.ProtoReflect.Descriptor instead.
func (*Data_Kafka) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Data_Kafka) GetBrokers() []string {
	if x != nil {
		return x.Brokers
	}
	return nil
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\"\xa9\x02\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x120\n" +
	"\bregistry\x18\x03 \x01(\v2\x14.kratos.api.RegistryR\bregistry\x121\n" +
	"\x06zaplog\x18\x04 \x01(\v2\x19.kratos.api.ZapLogConfigsR\x06zaplog\x123\n" +
	"\tschoolday\x18\x05 \x01(\v2\x15.kratos.api.SchoolDayR\tschoolday\x120\n" +
	"\bdefaults\x18\x06 \x01(\v2\x14.kratos.api.DefaultsR\bdefaults\"\x9b\x03\n" +
	"\x06Server\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x12\"\n" +
	"\fwaitCrawTime\x18\x03 \x01(\x05R\fwaitCrawTime\x12(\n" +
	"\x0fclassExpiration\x18\x04 \x01(\x05R\x0fclassExpiration\x12,\n" +
	"\x11recycleExpiration\x18\x05 \x01(\x05R\x11recycleExpiration\x120\n" +
	"\x13blackListExpiration\x18\x06 \x01(\x05R\x13blackListExpiration\x12(\n" +
	"\x0fwaitUserSvcTime\x18\a \x01(\x05R\x0fwaitUserSvcTime\x12(\n" +
	"\x0frefreshInterval\x18\b \x01(\x05R\x0frefreshInterval\x1aN\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x05R\atimeout\"\xbd\x03\n" +
	"\x04Data\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.kratos.api.Data.DatabaseR\bdatabase\x12,\n" +
	"\x05redis\x18\x02 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x12,\n" +
	"\x05kafka\x18\x03 \x01(\v2\x16.kratos.api.Data.KafkaR\x05kafka\x1a~\n" +
	"\bDatabase\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x19\n" +
	"\blog_path\x18\x02 \x01(\tR\alogPath\x12\"\n" +
	"\rlog_file_name\x18\x03 \x01(\tR\vlogFileName\x12\x1b\n" +
	"\tlog_level\x18\x04 \x01(\tR\blogLevel\x1a\x7f\n" +
	"\x05Redis\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12!\n" +
	"\fread_timeout\x18\x03 \x01(\x05R\vreadTimeout\x12#\n" +
	"\rwrite_timeout\x18\x04 \x01(\x05R\fwriteTimeout\x1a!\n" +
	"\x05Kafka\x12\x18\n" +
	"\abrokers\x18\x01 \x03(\tR\abrokers\"R\n" +
	"\x04Etcd\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"J\n" +
	"\bRegistry\x12$\n" +
	"\x04etcd\x18\x01 \x01(\v2\x10.kratos.api.EtcdR\x04etcd\x12\x18\n" +
	"\ausersvc\x18\x02 \x01(\tR\ausersvc\"\xc8\x02\n" +
	"\rZapLogConfigs\x12\x1b\n" +
	"\tlog_level\x18\x01 \x01(\tR\blogLevel\x12\x1d\n" +
	"\n" +
	"log_format\x18\x02 \x01(\tR\tlogFormat\x12\x19\n" +
	"\blog_path\x18\x03 \x01(\tR\alogPath\x12\"\n" +
	"\rlog_file_name\x18\x04 \x01(\tR\vlogFileName\x12)\n" +
	"\x11log_file_max_size\x18\x05 \x01(\x05R\x0elogFileMaxSize\x12/\n" +
	"\x14log_file_max_backups\x18\x06 \x01(\x05R\x11logFileMaxBackups\x12\x1e\n" +
	"\vlog_max_age\x18\a \x01(\x05R\tlogMaxAge\x12!\n" +
	"\flog_compress\x18\b \x01(\bR\vlogCompress\x12\x1d\n" +
	"\n" +
	"log_stdout\x18\t \x01(\bR\tlogStdout\"M\n" +
	"\tSchoolDay\x12 \n" +
	"\vholidayTime\x18\x01 \x01(\tR\vholidayTime\x12\x1e\n" +
	"\n" +
	"schoolTime\x18\x02 \x01(\tR\n" +
	"schoolTime\":\n" +
	"\bDefaults\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12\x1a\n" +
	"\bsemester\x18\x02 \x01(\tR\bsemesterB\x1eZ\x1cclasslist/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),     // 0: kratos.api.Bootstrap
	(*Server)(nil),        // 1: kratos.api.Server
	(*Data)(nil),          // 2: kratos.api.Data
	(*Etcd)(nil),          // 3: kratos.api.Etcd
	(*Registry)(nil),      // 4: kratos.api.Registry
	(*ZapLogConfigs)(nil), // 5: kratos.api.ZapLogConfigs
	(*SchoolDay)(nil),     // 6: kratos.api.SchoolDay
	(*Defaults)(nil),      // 7: kratos.api.Defaults
	(*Server_GRPC)(nil),   // 8: kratos.api.Server.GRPC
	(*Data_Database)(nil), // 9: kratos.api.Data.Database
	(*Data_Redis)(nil),    // 10: kratos.api.Data.Redis
	(*Data_Kafka)(nil),    // 11: kratos.api.Data.Kafka
}
var file_conf_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	4,  // 2: kratos.api.Bootstrap.registry:type_name -> kratos.api.Registry
	5,  // 3: kratos.api.Bootstrap.zaplog:type_name -> kratos.api.ZapLogConfigs
	6,  // 4: kratos.api.Bootstrap.schoolday:type_name -> kratos.api.SchoolDay
	7,  // 5: kratos.api.Bootstrap.defaults:type_name -> kratos.api.Defaults
	8,  // 6: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	9,  // 7: kratos.api.Data.database:type_name -> kratos.api.Data.Database
	10, // 8: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	11, // 9: kratos.api.Data.kafka:type_name -> kratos.api.Data.Kafka
	3,  // 10: kratos.api.Registry.etcd:type_name -> kratos.api.Etcd
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
