// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/bff/ioc"
	"github.com/asynccnu/ccnubox-be/bff/web/middleware"
)

// Injectors from wire.go:

func InitApp() *App {
	logger := ioc.InitLogger()
	loggerMiddleware := middleware.NewLoggerMiddleware(logger)
	cmdable := ioc.InitRedis()
	handler := ioc.InitJwtHandler(cmdable)
	loginMiddleware := middleware.NewLoginMiddleWare(handler)
	corsMiddleware := middleware.NewCorsMiddleware()
	basicAuthMiddleware := middleware.NewBasicAuthMiddleware()
	prometheusCounter := ioc.InitPrometheus()
	prometheusMiddleware := middleware.NewPrometheusMiddleware(prometheusCounter)
	client := ioc.InitEtcdClient()
	freeClassroomSvcClient := ioc.InitFreeClassroomClient(client)
	classRoomHandler := ioc.InitClassRoomHandler(freeClassroomSvcClient)
	putPolicy := ioc.InitPutPolicy()
	credentials := ioc.InitMac()
	tubeHandler := ioc.InitTubeHandler(putPolicy, credentials)
	userServiceClient := ioc.InitUserClient(client)
	userHandler := ioc.InitUserHandler(handler, userServiceClient)
	staticServiceClient := ioc.InitStaticClient(client)
	staticHandler := ioc.InitStaticHandler(staticServiceClient)
	bannerServiceClient := ioc.InitBannerClient(client)
	bannerHandler := ioc.InitBannerHandler(bannerServiceClient, userServiceClient)
	departmentServiceClient := ioc.InitDepartmentClient(client)
	departmentHandler := ioc.InitDepartmentHandler(departmentServiceClient)
	websiteServiceClient := ioc.InitWebsiteClient(client)
	websiteHandler := ioc.InitWebsiteHandler(websiteServiceClient)
	calendarServiceClient := ioc.InitCalendarClient(client)
	calendarHandler := ioc.InitCalendarHandler(calendarServiceClient)
	feedServiceClient := ioc.InitFeedClient(client)
	feedHandler := ioc.InitFeedHandler(feedServiceClient)
	elecpriceServiceClient := ioc.InitElecpriceClient(client)
	elecPriceHandler := ioc.InitElecpriceHandler(elecpriceServiceClient)
	gradeServiceClient := ioc.InitGradeClient(client)
	counterServiceClient := ioc.InitCounterClient(client)
	gradeHandler := ioc.InitGradeHandler(logger, gradeServiceClient, counterServiceClient)
	classerClient := ioc.InitClassList(client)
	classServiceClient := ioc.InitClassService(client)
	classHandler := ioc.InitClassHandler(classerClient, classServiceClient)
	feedbackHelpClient := ioc.InitFeedbackHelpClient(client)
	feedbackHelpHandler := ioc.InitFeedbackHelpHandler(feedbackHelpClient)
	infoSumServiceClient := ioc.InitInfoSumClient(client)
	infoSumHandler := ioc.InitInfoSumHandler(infoSumServiceClient)
	cardClient := ioc.InitCardClient(client)
	cardHandler := ioc.InitCardHandler(cardClient)
	metricsHandler := ioc.InitMetricsHandel(logger)
	libraryClient := ioc.InitLibrary(client)
	libraryHandler := ioc.InitLibraryHandler(libraryClient)
	swagHandler := ioc.InitSwagHandler(libraryClient)
	engine := ioc.InitGinServer(loggerMiddleware, loginMiddleware, corsMiddleware, basicAuthMiddleware, prometheusMiddleware, classRoomHandler, tubeHandler, userHandler, staticHandler, bannerHandler, departmentHandler, websiteHandler, calendarHandler, feedHandler, elecPriceHandler, gradeHandler, classHandler, feedbackHelpHandler, infoSumHandler, cardHandler, metricsHandler, libraryHandler, swagHandler)
	app := NewApp(engine)
	return app
}
