// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-department/grpc"
	"github.com/asynccnu/ccnubox-be/be-department/ioc"
	"github.com/asynccnu/ccnubox-be/be-department/pkg/grpcx"
	"github.com/asynccnu/ccnubox-be/be-department/repository/cache"
	"github.com/asynccnu/ccnubox-be/be-department/repository/dao"
	"github.com/asynccnu/ccnubox-be/be-department/service"
)

// Injectors from wire.go:

func InitGRPCServer() grpcx.Server {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	departmentDAO := dao.NewMysqlDepartmentDAO(db)
	cmdable := ioc.InitRedis()
	departmentCache := cache.NewRedisDepartmentCache(cmdable)
	departmentService := service.NewDepartmentService(departmentDAO, departmentCache, logger)
	departmentServiceServer := grpc.NewDepartmentServiceServer(departmentService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxKratosServer(departmentServiceServer, client, logger)
	return server
}
