// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-grade/cron"
	"github.com/asynccnu/ccnubox-be/be-grade/grpc"
	"github.com/asynccnu/ccnubox-be/be-grade/ioc"
	"github.com/asynccnu/ccnubox-be/be-grade/repository/dao"
	"github.com/asynccnu/ccnubox-be/be-grade/service"
)

// Injectors from wire.go:

func InitApp() App {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	gradeDAO := dao.NewGradeDAO(db)
	client := ioc.InitEtcdClient()
	userServiceClient := ioc.InitUserClient(client)
	gradeService := service.NewGradeService(gradeDAO, logger, userServiceClient)
	rankDAO := dao.NewRankDAO(db)
	rankService := service.NewRankService(rankDAO, logger, userServiceClient)
	gradeServiceServer := grpc.NewGradeGrpcService(gradeService, rankService)
	server := ioc.InitGRPCxKratosServer(gradeServiceServer, client, logger)
	counterServiceClient := ioc.InitCounterClient(client)
	feedServiceClient := ioc.InitFeedClient(client)
	classerClient := ioc.InitClasslistClient(client)
	gradeController := cron.NewGradeController(logger, counterServiceClient, userServiceClient, feedServiceClient, classerClient, gradeService, rankService)
	v := cron.NewCron(gradeController)
	app := NewApp(server, v)
	return app
}
