// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/biz"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/classLog"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/client"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/conf"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/data"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/pkg/crawler"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/registry"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/server"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"os"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confRegistry *conf.Registry, schoolDay *conf.SchoolDay, file *os.File, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, file)
	dataData, cleanup, err := data.NewData(confData, db, logger)
	if err != nil {
		return nil, nil, err
	}
	helper := classLog.NewClogger(logger)
	classInfoDBRepo := data.NewClassInfoDBRepo(dataData, helper)
	redisClient := data.NewRedisDB(confData)
	classInfoCacheRepo := data.NewClassInfoCacheRepo(redisClient, helper)
	classInfoRepo := biz.NewClassInfoRepo(classInfoDBRepo, classInfoCacheRepo)
	studentAndCourseDBRepo := data.NewStudentAndCourseDBRepo(dataData, helper)
	studentAndCourseCacheRepo := data.NewStudentAndCourseCacheRepo(redisClient, helper)
	studentAndCourseRepo := biz.NewStudentAndCourseRepo(studentAndCourseDBRepo, studentAndCourseCacheRepo)
	classRepo := biz.NewClassRepo(classInfoRepo, dataData, studentAndCourseRepo, logger)
	crawlerCrawler := crawler.NewClassCrawler(helper)
	jxbDBRepo := data.NewJxbDBRepo(dataData, helper)
	etcdRegistry := registry.NewRegistrarServer(confRegistry, logger)
	userServiceClient, err := client.NewClient(etcdRegistry, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	ccnuService := client.NewCCNUService(userServiceClient)
	classUsercase := biz.NewClassUsecase(classRepo, crawlerCrawler, jxbDBRepo, ccnuService, logger)
	classerService := service.NewClasserService(classUsercase, schoolDay, logger)
	grpcServer := server.NewGRPCServer(confServer, classerService, logger)
	app := newApp(logger, grpcServer, etcdRegistry)
	return app, func() {
		cleanup()
	}, nil
}
