// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/biz"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/client"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/conf"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/data"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/pkg/crawler"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/registry"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/server"
	"github.com/asynccnu/ccnubox-be/be-classlist/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"os"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confRegistry *conf.Registry, schoolDay *conf.SchoolDay, file *os.File, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, file, logger)
	dataData, cleanup, err := data.NewData(confData, db, logger)
	if err != nil {
		return nil, nil, err
	}
	classInfoDBRepo := data.NewClassInfoDBRepo(dataData, logger)
	redisClient := data.NewRedisDB(confData, logger)
	classInfoCacheRepo := data.NewClassInfoCacheRepo(redisClient, confServer, logger)
	classInfoRepo := data.NewClassInfoRepo(classInfoDBRepo, classInfoCacheRepo)
	studentAndCourseDBRepo := data.NewStudentAndCourseDBRepo(dataData, logger)
	studentAndCourseCacheRepo := data.NewStudentAndCourseCacheRepo(redisClient, confServer, logger)
	studentAndCourseRepo := data.NewStudentAndCourseRepo(studentAndCourseDBRepo, studentAndCourseCacheRepo)
	classRepo := data.NewClassRepo(classInfoRepo, dataData, studentAndCourseRepo, logger)
	crawler2 := crawler.NewClassCrawler2(logger)
	jxbDBRepo := data.NewJxbDBRepo(dataData, logger)
	etcdRegistry := registry.NewRegistrarServer(confRegistry, logger)
	userServiceClient, err := client.NewClient(etcdRegistry, confRegistry, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	ccnuService := client.NewCCNUService(userServiceClient)
	kafkaProducerBuilder := data.NewKafkaProducerBuilder(confData)
	kafkaConsumerBuilder := data.NewKafkaConsumerBuilder(confData)
	delayKafkaConfig := data.NewDelayKafkaConfig()
	delayKafka, cleanup2, err := data.NewDelayKafka(kafkaProducerBuilder, kafkaConsumerBuilder, delayKafkaConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	refreshLogRepo := data.NewRefreshLogRepo(db, confServer)
	classUsecase, cleanup3 := biz.NewClassUsecase(classRepo, crawler2, jxbDBRepo, ccnuService, delayKafka, refreshLogRepo, confServer, logger)
	classListService := service.NewClasserService(classUsecase, schoolDay, logger)
	grpcServer := server.NewGRPCServer(confServer, classListService, logger)
	app := newApp(logger, grpcServer, etcdRegistry)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
