// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-ccnu/crawler"
	"github.com/asynccnu/ccnubox-be/be-ccnu/grpc"
	"github.com/asynccnu/ccnubox-be/be-ccnu/ioc"
	"github.com/asynccnu/ccnubox-be/be-ccnu/pkg/grpcx"
	"github.com/asynccnu/ccnubox-be/be-ccnu/service"
)

// Injectors from wire.go:

func InitGRPCServer() grpcx.Server {
	logger := ioc.InitLogger()
	client := crawler.NewCrawlerClient()
	passport := crawler.NewPassport(client)
	ccnuService := service.NewCCNUService(logger, passport)
	ccnuServiceServer := grpc.NewCCNUServiceServer(ccnuService)
	clientv3Client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxKratosServer(ccnuServiceServer, clientv3Client, logger)
	return server
}
