// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-website/grpc"
	"github.com/asynccnu/ccnubox-be/be-website/ioc"
	"github.com/asynccnu/ccnubox-be/be-website/pkg/grpcx"
	"github.com/asynccnu/ccnubox-be/be-website/repository/cache"
	"github.com/asynccnu/ccnubox-be/be-website/repository/dao"
	"github.com/asynccnu/ccnubox-be/be-website/service"
)

// Injectors from wire.go:

func InitGRPCServer() grpcx.Server {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	websiteDAO := dao.NewMysqlWebsiteDAO(db)
	cmdable := ioc.InitRedis()
	websiteCache := cache.NewRedisWebsiteCache(cmdable)
	websiteService := service.NewWebsiteService(websiteDAO, websiteCache, logger)
	websiteServiceServer := grpc.NewWebsiteServiceServer(websiteService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxKratosServer(websiteServiceServer, client, logger)
	return server
}
