// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-class/internal/biz"
	"github.com/asynccnu/ccnubox-be/be-class/internal/client"
	"github.com/asynccnu/ccnubox-be/be-class/internal/conf"
	"github.com/asynccnu/ccnubox-be/be-class/internal/data"
	"github.com/asynccnu/ccnubox-be/be-class/internal/lock"
	"github.com/asynccnu/ccnubox-be/be-class/internal/registry"
	"github.com/asynccnu/ccnubox-be/be-class/internal/server"
	"github.com/asynccnu/ccnubox-be/be-class/internal/service"
	"github.com/asynccnu/ccnubox-be/be-class/internal/timedTask"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confRegistry *conf.Registry, logger log.Logger) (*APP, func(), error) {
	elasticClient, err := data.NewEsClient(confData)
	if err != nil {
		return nil, nil, err
	}
	classData, cleanup, err := data.NewClassData(elasticClient)
	if err != nil {
		return nil, nil, err
	}
	etcdRegistry := registry.NewRegistrarServer(confRegistry)
	classListService, err := client.NewClassListService(etcdRegistry)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	redisClient := data.NewRedisClient(confData)
	builder := lock.NewRedisLockBuilder(redisClient)
	cache := data.NewCache(redisClient)
	classServiceUserCase := biz.NewClassServiceUserCase(classData, classListService, builder, cache)
	classServiceService := service.NewClassServiceService(classServiceUserCase)
	freeClassroomData := data.NewFreeClassroomData(elasticClient)
	cookieSvc, err := client.NewCookieSvc(etcdRegistry)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	freeClassroomBiz := biz.NewFreeClassroomBiz(classData, freeClassroomData, cookieSvc, builder, cache)
	freeClassroomSvc := service.NewFreeClassroomSvc(freeClassroomBiz)
	grpcServer := server.NewGRPCServer(confServer, classServiceService, freeClassroomSvc, logger)
	selectionUploader := service.NewSelectionUploader(freeClassroomBiz)
	httpServer := server.NewHTTPServer(confServer, selectionUploader)
	app := newApp(logger, grpcServer, httpServer, etcdRegistry)
	task := timedTask.NewTask(classServiceUserCase, freeClassroomBiz, classListService)
	mainAPP := NewApp(app, task)
	return mainAPP, func() {
		cleanup()
	}, nil
}
