// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-library/internal/biz"
	"github.com/asynccnu/ccnubox-be/be-library/internal/client"
	"github.com/asynccnu/ccnubox-be/be-library/internal/conf"
	"github.com/asynccnu/ccnubox-be/be-library/internal/crawler"
	"github.com/asynccnu/ccnubox-be/be-library/internal/data"
	"github.com/asynccnu/ccnubox-be/be-library/internal/registry"
	"github.com/asynccnu/ccnubox-be/be-library/internal/server"
	"github.com/asynccnu/ccnubox-be/be-library/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confRegistry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	cookiePool := client.NewCookiePoolProvider()
	etcdRegistry := registry.NewRegistrarServer(confRegistry, logger)
	userServiceClient, err := client.NewClient(etcdRegistry, confRegistry, logger)
	if err != nil {
		return nil, nil, err
	}
	ccnuServiceProxy := client.NewCCNUServiceProxy(userServiceClient)
	duration := biz.NewWaitTime(confServer)
	libraryCrawler := crawler.NewLibraryCrawler(logger, cookiePool, ccnuServiceProxy, duration)
	db, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	redisClient := data.NewRedisDB(confData, logger)
	dataData, err := data.NewData(confData, logger, db, redisClient)
	if err != nil {
		return nil, nil, err
	}
	seatRepo := data.NewSeatRepo(dataData, logger, libraryCrawler)
	libraryBiz := biz.NewLibraryBiz(libraryCrawler, logger, seatRepo)
	assembler := data.NewAssembler()
	commentRepo := data.NewCommentRepo(dataData, logger, assembler)
	libraryService := service.NewLibraryService(libraryBiz, logger, commentRepo)
	grpcServer := server.NewGRPCServer(confServer, libraryService, logger)
	app := newApp(logger, grpcServer, etcdRegistry)
	return app, func() {
	}, nil
}
