// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-calendar/cron"
	"github.com/asynccnu/ccnubox-be/be-calendar/grpc"
	"github.com/asynccnu/ccnubox-be/be-calendar/ioc"
	"github.com/asynccnu/ccnubox-be/be-calendar/repository/cache"
	"github.com/asynccnu/ccnubox-be/be-calendar/repository/dao"
	"github.com/asynccnu/ccnubox-be/be-calendar/service"
)

// Injectors from wire.go:

func InitApp() App {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	calendarDAO := dao.NewMysqlCalendarDAO(db)
	cmdable := ioc.InitRedis()
	calendarCache := cache.NewRedisCalendarCache(cmdable)
	calendarService := service.NewCachedCalendarService(calendarDAO, calendarCache, logger)
	calendarServiceServer := grpc.NewCalendarServiceServer(calendarService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxKratosServer(calendarServiceServer, client, logger)
	qiniuClient := ioc.InitQiniu()
	calendarController := cron.NewCalendarController(calendarService, qiniuClient, logger)
	feedServiceClient := ioc.InitFeedClient(client)
	holidayController := cron.NewHolidayController(feedServiceClient, logger)
	v := cron.NewCron(calendarController, holidayController)
	app := NewApp(server, v)
	return app
}
